// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD52SOM5s1kUJapsbN6RzF9KNfJEaBjlUc',
    appId: '1:724668581926:web:6b919e2aae679a93abfee7',
    messagingSenderId: '724668581926',
    projectId: 'fruit-hub-69f2d',
    authDomain: 'fruit-hub-69f2d.firebaseapp.com',
    storageBucket: 'fruit-hub-69f2d.appspot.com',
    measurementId: 'G-55VVR3M7XH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8qTPbFyIT_DxYA_JH1w5JdKmPXKsvhKY',
    appId: '1:724668581926:android:d3f5696093ad5ca0abfee7',
    messagingSenderId: '724668581926',
    projectId: 'fruit-hub-69f2d',
    storageBucket: 'fruit-hub-69f2d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCze2RrLntOKDAlFGN4R2NNlpS-dmXcO_4',
    appId: '1:724668581926:ios:e10b8dd4a196e27cabfee7',
    messagingSenderId: '724668581926',
    projectId: 'fruit-hub-69f2d',
    storageBucket: 'fruit-hub-69f2d.appspot.com',
    androidClientId: '724668581926-93r04hfcjd0244p3gr54fhnbo8mnnvfs.apps.googleusercontent.com',
    iosClientId: '724668581926-elmvt0tat0u6b3sg3msm1b8oi5usr0hv.apps.googleusercontent.com',
    iosBundleId: 'com.example.fruitHubDashboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCze2RrLntOKDAlFGN4R2NNlpS-dmXcO_4',
    appId: '1:724668581926:ios:e10b8dd4a196e27cabfee7',
    messagingSenderId: '724668581926',
    projectId: 'fruit-hub-69f2d',
    storageBucket: 'fruit-hub-69f2d.appspot.com',
    androidClientId: '724668581926-93r04hfcjd0244p3gr54fhnbo8mnnvfs.apps.googleusercontent.com',
    iosClientId: '724668581926-elmvt0tat0u6b3sg3msm1b8oi5usr0hv.apps.googleusercontent.com',
    iosBundleId: 'com.example.fruitHubDashboard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD52SOM5s1kUJapsbN6RzF9KNfJEaBjlUc',
    appId: '1:724668581926:web:20e05eca3d79d9e7abfee7',
    messagingSenderId: '724668581926',
    projectId: 'fruit-hub-69f2d',
    authDomain: 'fruit-hub-69f2d.firebaseapp.com',
    storageBucket: 'fruit-hub-69f2d.appspot.com',
    measurementId: 'G-LL1ZW8X34F',
  );
}
